openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    Kişisel bir kişi rehberini yönetmek için kullanılan bir API. # 3. Açıklama eklendi
    Kullanıcı kimlik doğrulaması, kişi ekleme, silme, güncelleme ve
    listeleme işlemlerini destekler.
tags:
  - name: Contacts
    description: Kişilerle ilgili işlemler
  - name: Auth
    description: Kimlik doğrulama ile ilgili işlemler
servers:
  - url: http://localhost:3000
    description: Yerel geliştirme sunucusu
  - url: https://your-project-name.onrender.com
    description: Yayın sunucusu (Render.com)
paths:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
